name: Jamaican Stock Tracker
on:
  schedule:
    - cron: '0 17 * * 1-5'  # 12PM Jamaica time, Mon-Fri (market hours)
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Increased to 120 minutes
    env:
      TZ: America/Jamaica  # Set timezone for proper scheduling
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      ALERT_WEBHOOK_URL: ${{ secrets.ALERT_WEBHOOK_URL }}
      EMAIL_WEBHOOK_URL: ${{ secrets.EMAIL_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'  # Faster installs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install -y python3-dev libxml2-dev libxslt-dev  # For news parsing

      - name: Run scraper
        id: scraper
        continue-on-error: true
        run: |
          mkdir -p logs
          timeout 110m python scraper.py > logs/scraper_$(date +%Y%m%d).log 2>&1 || echo "Scraper timed out or failed, proceeding"
        timeout-minutes: 110

      - name: Check scraper success
        if: steps.scraper.outcome != 'success'
        run: |
          echo "Scraper step failed or timed out. Checking logs..."
          if ! grep -q "Saved" logs/scraper_$(date +%Y%m%d).log; then
            echo "No data saved, skipping report generation"
            exit 1
          fi

      - name: Generate report
        if: success() || steps.scraper.outcome == 'failure'  # Run even if scraper fails
        run: |
          python report.py > logs/report_$(date +%Y%m%d).log 2>&1

      - name: Send Discord notification
        run: |
          python notifier.py > logs/notifier_$(date +%Y%m%d).log 2>&1

      - name: Archive data
        uses: actions/upload-artifact@v4
        with:
          name: stock-data-${{ github.run_id }}
          path: |
            data/*.csv
            report.pdf
            price_chart.png
            wordcloud.png
            volume_chart.png
            deepsite_data.json
            logs/*.log
          retention-days: 7

      - name: Slack notification
        if: always() && env.SLACK_WEBHOOK_URL
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Stock tracker ${{ job.status }}: ${{ github.repository }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Jamaican Stock Tracker* \nStatus: ${{ job.status }}\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}