name: Jamaican Stock Tracker
on:
  schedule:
    - cron: '0 17 * * 1-5'  # 12PM Jamaica time, Mon-Fri (market hours)
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Prevent hanging
    env:
      TZ: America/Jamaica  # Set timezone for proper scheduling
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      ALERT_WEBHOOK_URL: ${{ secrets.ALERT_WEBHOOK_URL }}
      EMAIL_WEBHOOK_URL: ${{ secrets.EMAIL_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'  # Faster installs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install -y python3-dev libxml2-dev libxslt-dev  # For news parsing

      - name: Run scraper
        run: |
          mkdir -p logs
          python scraper.py > logs/scraper_$(date +%Y%m%d).log 2>&1

      - name: Generate report
        run: |
          python report.py > logs/report_$(date +%Y%m%d).log 2>&1

      - name: Send Discord notification
        run: |
          python notifier.py > logs/notifier_$(date +%Y%m%d).log 2>&1

      - name: Archive data
        uses: actions/upload-artifact@v4
        with:
          name: stock-data-${{ github.run_id }}
          path: |
            data/*.csv
            report.pdf
            logs/*.log
          retention-days: 7

      - name: Slack notification
        if: always() && env.SLACK_WEBHOOK_URL
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Stock tracker ${{ job.status }}: ${{ github.repository }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Jamaican Stock Tracker* \nStatus: ${{ job.status }}\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
