name: Jamaican Stock Tracker
on:
  schedule:
    - cron: '0 18 * * *'  # 1 PM Jamaica time
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install -r requirements.txt
      - run: python scraper.py
      - uses: actions/upload-artifact@v3
        with:
          name: stock-data
          path: data/
      - uses: dawidd6/action-send-mail@v3
        if: github.event_name == 'schedule'
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Jamaican Stock Report - $(date +'%Y-%m-%d')"
          body: "Attached: CEO tweets, Reddit discussions, and news."
          to: ${{ secrets.EMAIL_USER }}
          from: "GitHub Actions"
          attachments: data/*.csv
